//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDevice
    {
        public string Device_ID { get; set; }
        public string Device_Name { get; set; }
        public string Device_category_ID { get; set; }
        public string Device_Site_ID { get; set; }
        public string Device_Description { get; set; }
        public string UserEntry { get; set; }
        public System.DateTime DateEntry { get; set; }
        public string UserLastMaintenance { get; set; }
        public Nullable<System.DateTime> DateLastMaintenance { get; set; }
    }
}
