//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSensorParameter
    {
        public string ID_Param { get; set; }
        public string ID_Category { get; set; }
        public string ID_Sensor_Detail { get; set; }
        public decimal Lower_Limit { get; set; }
        public decimal Upper_Limit { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserEntry { get; set; }
        public Nullable<System.DateTime> DateLastMaintenance { get; set; }
        public string UserLastMaintenance { get; set; }
    }
}
