//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceWebAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDetailGroupSensor
    {
        public string ID_Detail_Group_Sensor { get; set; }
        public string Detail_SensorName { get; set; }
        public string ID_Main_Group { get; set; }
        public string Description { get; set; }
        public string unit { get; set; }
    }
}
